# Generated by Django 4.1.7 on 2023-03-07 14:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("items_count", models.IntegerField(default=0)),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PEDIDO REALIZADO", "Request Made"),
                            ("EM ANDAMENTO", "In Progress"),
                            ("CONCLUÍDO", "Done"),
                        ],
                        default="PEDIDO REALIZADO",
                        max_length=50,
                    ),
                ),
                ("crated_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
