# Generated by Django 4.1.7 on 2023-03-07 15:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_initial"),
        ("carts", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="products",
            field=models.ManyToManyField(
                related_name="cart_products", to="products.product"
            ),
        ),
    ]
