# Generated by Django 4.1.7 on 2023-03-09 14:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_rename_is_avaliable_product_is_available"),
        ("carts", "0003_cart_products"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="products",
        ),
        migrations.AlterField(
            model_name="cart",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDENTE", "Pending"),
                    ("PEDIDO REALIZADO", "Request Made"),
                    ("EM ANDAMENTO", "In Progress"),
                    ("CONCLUÍDO", "Done"),
                ],
                default="PENDENTE",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="total_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.CreateModel(
            name="CartProduct",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.IntegerField()),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="carts.cart"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="cart",
            name="carts_products",
            field=models.ManyToManyField(
                through="carts.CartProduct", to="products.product"
            ),
        ),
    ]
