# Generated by Django 4.1.7 on 2023-03-09 19:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("carts", "0004_remove_cart_products_alter_cart_status_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cart",
            old_name="carts_products",
            new_name="products",
        ),
    ]
