# Generated by Django 4.1.7 on 2023-03-07 17:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="is_avaliable",
            new_name="is_available",
        ),
    ]
